server:
  port: 4000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HeeralalGupta/config_server_properties.git
          clone-on-start: true
          
  application:
   name: Config Server
   
management:
  security:
    enabled: false