management:
  endpoints:
    web:
      exposure:
        include: '*'
        
server:
  port: 1002
  
spring:
  application:
    name: Welcome-Microservice
  boot:
    admin:
      client:
        url: http://localhost:1212/

  config:
    import: optional:configserver:http://localhost:4000